notificacion:
  webhook:
    url: https://n8nworkflows1.app.n8n.cloud/webhook-test/8f2c9a7d-75d0-4d11-a998-1c08377d52b1

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: arka
    password: arka123